# Generated by Django 6.0.6 on 2026-07-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weblug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=10)),
                ('titr1', models.CharField(max_length=150)),
                ('paragraph1', models.TextField()),
                ('titr2', models.CharField(max_length=150)),
                ('paragraph2', models.TextField()),
                ('titr3', models.CharField(max_length=150)),
                ('paragraph3', models.TextField()),
                ('titr4', models.CharField(max_length=150)),
                ('paragraph4', models.TextField()),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
