# Generated by Django 6.0.6 on 2026-07-28 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Weblug',
        ),
    ]
