# Generated by Django 6.0.6 on 2026-07-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weblug',
            old_name='img',
            new_name='img1',
        ),
        migrations.AddField(
            model_name='weblug',
            name='img2',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weblug',
            name='img3',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weblug',
            name='img4',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weblug',
            name='paragraph2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weblug',
            name='paragraph3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weblug',
            name='paragraph4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weblug',
            name='titr2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='weblug',
            name='titr3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='weblug',
            name='titr4',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
