# Generated by Django 6.0.6 on 2026-07-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_img_weblug_img1_weblug_img2_weblug_img3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weblug',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='weblug',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='weblug',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
