# Generated by Django 6.0.6 on 2026-07-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_weblug_img2_alter_weblug_img3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weblug',
            name='daste',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weblug',
            name='virast',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
