# Generated by Django 6.0.6 on 2026-07-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_weblug_daste_weblug_virast'),
    ]

    operations = [
        migrations.AddField(
            model_name='weblug',
            name='minp',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
