# Generated by Django 6.0.6 on 2026-07-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_weblug_minp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weblug',
            name='img1',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='weblug',
            name='img2',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weblug',
            name='img3',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weblug',
            name='img4',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
