# Generated by Django 6.0.6 on 2026-07-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_weblug_img1_alter_weblug_img2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weblug',
            name='img2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='weblug',
            name='img3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='weblug',
            name='img4',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
