# Generated by Django 6.0.6 on 2026-07-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_weblug_img2_alter_weblug_img3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weblug',
            name='img1',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='weblug',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='weblug',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='weblug',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
