# Generated by Django 6.0.6 on 2026-07-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_weblug_img1_alter_weblug_img2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('ostan', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('phoneNumber', models.IntegerField()),
                ('decryption', models.TextField()),
            ],
        ),
    ]
