# Generated by Django 6.0.6 on 2026-07-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='phoneNumber',
            field=models.CharField(max_length=11),
        ),
    ]
