# Generated by Django 6.0.6 on 2026-07-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_agent_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
