# Generated by Django 6.0.6 on 2026-07-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_agent_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('phoneNumber', models.CharField(max_length=11)),
                ('businessName', models.CharField(max_length=50)),
                ('productPrice', models.CharField(max_length=50)),
                ('productName', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
