# Generated by Django 6.0.6 on 2026-07-29 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_lastform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lastform',
            old_name='phoneNumber',
            new_name='phone',
        ),
    ]
