# Generated by Django 6.0.6 on 2026-07-29 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_rename_phonenumber_lastform_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lastform',
            old_name='lastName',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='lastform',
            old_name='productName',
            new_name='version',
        ),
        migrations.RemoveField(
            model_name='lastform',
            name='productPrice',
        ),
    ]
