# Generated by Django 6.0.6 on 2026-07-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_rename_lastname_lastform_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastform',
            name='firstName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
