# Generated by Django 6.0.6 on 2026-07-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_alter_lastform_address_alter_lastform_businessname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastform',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lastform',
            name='businessName',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
           model_name='lastform',
           name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lastform',
            name='firstName',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lastform',
            name='lastname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lastform',
            name='phone',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lastform',
            name='version',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
