# Generated by Django 6.0.6 on 2026-08-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_alter_lastform_address_alter_lastform_businessname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameApp', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=50)),
                ('download1', models.FileField(upload_to='')),
                ('download2', models.FileField(upload_to='')),
            ],
        ),
    ]
