# Generated by Django 6.0.6 on 2026-08-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_downloadrequirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadrequirements',
            name='download1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='downloadrequirements',
            name='download2',
            field=models.TextField(),
        ),
    ]
