# Generated by Django 6.0.6 on 2026-08-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_alter_downloadrequirements_download1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadrequirements',
            name='download1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='downloadrequirements',
            name='download2',
            field=models.URLField(blank=True, null=True),
        ),
    ]
