# Generated by Django 6.0.6 on 2026-08-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='businessName',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
