# Generated by Django 6.0.6 on 2026-08-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_customer_businessname'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastform',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
