# Generated by Django 6.0.6 on 2026-07-28 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_weblug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Weblug',
        ),
    ]
